CREATE FUNCTION DBO.FN_GET_CURRENT_IP ()
RETURNS VARCHAR(255)
AS
BEGIN
    DECLARE @IP_ADDRESS VARCHAR(255);

    SELECT @IP_ADDRESS = CLIENT_NET_ADDRESS
    FROM SYS.DM_EXEC_CONNECTIONS
    WHERE SESSION_ID = @@SPID;

    RETURN @IP_ADDRESS;
END