CREATE TABLE DATA.CONTACTABILITY_1 (
  HISTORY_DATE INTEGER NOT NULL,
  PRODUCT_KEY INTEGER NOT NULL,
  NEGOTIATOR_KEY INTEGER NOT NULL,
  TOTAL_CALLS INTEGER NOT NULL,
  SUCCESSFUL_CONTACTS INTEGER NOT NULL,
  CONSTRAINT FK_CONT1_HISTORY_DATE FOREIGN KEY (HISTORY_DATE)
    REFERENCES DATA.DIM_DATE(DATE_KEY),
  CONSTRAINT FK_CONT1_PRODUCT_KEY FOREIGN KEY (PRODUCT_KEY)
    REFERENCES DATA.DIM_PRODUCT(PRODUCT_KEY),
  CONSTRAINT FK_CONT1_NEGOTIATOR_KEY FOREIGN KEY (NEGOTIATOR_KEY)
    REFERENCES DATA.DIM_NEGOTIATOR(NEGOTIATOR_KEY)
);