-- CREATE TABLE
CREATE TABLE STAGE.FACT_NEGOTATION (
  CREDIT_CODE VARCHAR(100),
  ACTION_NAME VARCHAR(255),
  RESPONSE_NAME VARCHAR(255),
  CONTACT_NAME VARCHAR(255),
  NEGOTIATOR_CODE VARCHAR(100),
  CARRIER_NAME VARCHAR(255),
  HISTORY_DATE CHAR(8), /* YYYYMMDD */
  OBSERVATION NVARCHAR(1500),
  TELEPHONE_NUMBER VARCHAR(255),
  TELEPHONE_STATUS VARCHAR(255),
  PROMISE_AMNT VARCHAR(255),
  PROMISE_NEXT_DATE CHAR(8),
  CREATION_DATE VARCHAR(255),
  FLAG CHAR(1)
);