-- CREATE TABLE
CREATE TABLE DATA.FACT_NEGOTATION_1 (
  CREDIT_KEY INTEGER NOT NULL,
  ACTION_KEY INTEGER NOT NULL,
  RESPONSE_KEY INTEGER NOT NULL,
  CONTACT_KEY INTEGER NOT NULL,
  NEGOTIATOR_KEY INTEGER NOT NULL,
  CARRIER_NAME VARCHAR(255),
  HISTORY_DATE INTEGER NOT NULL,
  OBSERVATION NVARCHAR(1500),
  TELEPHONE_NUMBER VARCHAR(255),
  TELEPHONE_STATUS VARCHAR(255),
  PROMISE_AMNT DECIMAL(18,2),
  PROMISE_NEXT_DATE INTEGER,
  FLAG CHAR(1),
  CREATION_USER VARCHAR(100) NOT NULL CONSTRAINT DF_FACTNEGOTATION1_CREATIONUSER DEFAULT CAST(SERVERPROPERTY('ServerName') AS NVARCHAR) + '-' + CAST(SERVERPROPERTY('MachineName') AS NVARCHAR),
  CREATION_DATE DATETIME NOT NULL CONSTRAINT DF_FACTNEGOTATION1_CREATIONDATE DEFAULT GETDATE(),
  CREATION_IP VARCHAR(50) NOT NULL CONSTRAINT DF_FACTNEGOTATION1_CREATIONIP DEFAULT DBO.FN_GET_CURRENT_IP(),
  MODIFICATION_USER VARCHAR(100) NULL,
  MODIFICATION_DATE DATETIME NULL,
  MODIFICATION_IP VARCHAR(50) NULL,
  CONSTRAINT FK_FACTNEG1_DIMCRED_CREDITKEY FOREIGN KEY (CREDIT_KEY)
    REFERENCES DATA.DIM_CREDIT(CREDIT_KEY),
  CONSTRAINT FK_FACTNEG1_DIMACT_ACTIONKEY FOREIGN KEY (ACTION_KEY)
    REFERENCES DATA.DIM_ACTION(ACTION_KEY),
  CONSTRAINT FK_FACTNEG1_DIMRESP_RESPONSEKEY FOREIGN KEY (RESPONSE_KEY)
    REFERENCES DATA.DIM_RESPONSE(RESPONSE_KEY),
  CONSTRAINT FK_FACTNEG1_DIMCON_CONTACTKEY FOREIGN KEY (CONTACT_KEY)
    REFERENCES DATA.DIM_CONTACT(CONTACT_KEY),
  CONSTRAINT FK_FACTNEG1_DIMNEG_NEGOTIATORKEY FOREIGN KEY (NEGOTIATOR_KEY)
    REFERENCES DATA.DIM_NEGOTIATOR(NEGOTIATOR_KEY),
  CONSTRAINT FK_FACTNEG1_DIMDATE_HISTORYDATE FOREIGN KEY (HISTORY_DATE)
    REFERENCES DATA.DIM_DATE(DATE_KEY)
);