CREATE TABLE DATA.DIM_DATE (
  DATE_KEY INTEGER NOT NULL /* formato YYYYMMDD*/,
  FULL_DATE_ALTERNATE_KEY DATE NOT NULL,
  CALENDAR_YEAR CHAR(4) NOT NULL, /* YYYY */
  CALENDAR_YEAR_MONTH CHAR(6) NOT NULL, /* YYYYMM */
  CALENDAR_SEMESTER_OF_YEAR TINYINT NOT NULL, /* 1 to 2 */
  CALENDAR_QUARTER_OF_YEAR TINYINT NOT NULL, /* 1 to 4 */
  CALENDAR_SEMESTER_OF_YEAR_DESCRIPTION CHAR(2) NULL, /* S1 to S2 */
  CALENDAR_QUARTER_OF_YEAR_DESCRIPTION CHAR(2) NULL, /* Q1 to Q4 */
  MONTH_NUMBER_OF_YEAR TINYINT NOT NULL, /* 1 to 12 */
  WEEK_NUMBER_OF_MONTH TINYINT NOT NULL, /* 1 to 4 */
  WEEK_NUMBER_OF_MONTH_DESCRIPTION CHAR(4) NOT NULL, /* SEM1 to SEM5 */
  DAY_NUMBER_OF_MONTH INTEGER NOT NULL, /* 1 to 31 */
  SPANISH_MONTH_NAME NVARCHAR(10) NULL, /* Enero to Diciembre */
  CREATION_USER VARCHAR(100) NOT NULL CONSTRAINT DF_DIMDATE_CREATIONUSER DEFAULT CAST(SERVERPROPERTY('ServerName') AS NVARCHAR) + '-' + CAST(SERVERPROPERTY('MachineName') AS NVARCHAR),
  CREATION_DATE DATETIME NOT NULL CONSTRAINT DF_DIMDATE_CREATIONDATE DEFAULT GETDATE(),
  CREATION_IP VARCHAR(50) NOT NULL CONSTRAINT DF_DIMDATE_CREATIONIP DEFAULT DBO.FN_GET_CURRENT_IP(),
  MODIFICATION_USER VARCHAR(100) NULL,
  MODIFICATION_DATE DATETIME NULL,
  MODIFICATION_IP VARCHAR(50) NULL
  CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_KEY)
);