CREATE TABLE DATA.FACT_PAYMENT_1 (
  CREDIT_KEY INTEGER NOT NULL,
  PAYMENT_DATE INTEGER NOT NULL,
  CURRENCY_KEY CHAR(3) NOT NULL,
  AMOUNT DECIMAL(18,2) NOT NULL,
  CREATION_USER VARCHAR(100) NOT NULL CONSTRAINT DF_FACTPAYMENT1_CREATIONUSER DEFAULT CAST(SERVERPROPERTY('ServerName') AS NVARCHAR) + '-' + CAST(SERVERPROPERTY('MachineName') AS NVARCHAR),
  CREATION_DATE DATETIME NOT NULL CONSTRAINT DF_FACTPAYMENT1_CREATIONDATE DEFAULT GETDATE(),
  CREATION_IP VARCHAR(50) NOT NULL CONSTRAINT DF_FACTPAYMENT1_CREATIONIP DEFAULT DBO.FN_GET_CURRENT_IP(),
  MODIFICATION_USER VARCHAR(100) NULL,
  MODIFICATION_DATE DATETIME NULL,
  MODIFICATION_IP VARCHAR(50) NULL,
  CONSTRAINT FK_FACTPAY1_DIMCRED_CREDITKEY FOREIGN KEY (CREDIT_KEY)
    REFERENCES DATA.DIM_CREDIT(CREDIT_KEY),
  CONSTRAINT FK_FACTPAY1_DIMDATE_PYMNTDATE FOREIGN KEY (PAYMENT_DATE)
    REFERENCES DATA.DIM_DATE(DATE_KEY),
  CONSTRAINT FK_FACTPAY1_DIMCUR_CURRENCYKEY FOREIGN KEY (CURRENCY_KEY)
    REFERENCES DATA.DIM_CURRENCY(CURRENCY_KEY)
);