CREATE PROCEDURE STAGE.SP_BUILD_CONTACTABILITY AS

BEGIN

  BEGIN TRY

  -- STEP 01: CREATE TABLE DATA.CONTACTABILITY_1_PREV
  IF OBJECT_ID(N'[CIP_DM].[DATA].[CONTACTABILITY_1_PREV]',N'U') IS NOT NULL DROP TABLE CIP_DM.DATA.CONTACTABILITY_1_PREV;

SELECT
    N.HISTORY_DATE,
    C.PRODUCT_KEY,
    N.NEGOTIATOR_KEY,
    COUNT(N.RESPONSE_KEY) AS TOTAL_CALLS,
    COUNT(CASE WHEN N.RESPONSE_KEY = 1 OR N.RESPONSE_KEY = 3 THEN 1 ELSE NULL END) AS SUCCESSFUL_CONTACTS
  INTO DATA.CONTACTABILITY_1_PREV
  FROM DATA.FACT_NEGOTATION N
   INNER JOIN DATA.DIM_CREDIT C
  ON C.CREDIT_KEY = N.CREDIT_KEY
  INNER JOIN DATA.DIM_PRODUCT O
  ON O.PRODUCT_KEY = C.PRODUCT_KEY
  WHERE N.ACTION_KEY = 1
   GROUP BY N.HISTORY_DATE, C.PRODUCT_KEY, N.NEGOTIATOR_KEY
   ORDER BY N.HISTORY_DATE ASC;

  -- STEP 02: CREATE INDEXES AND CONSTRAINTS DATA.CONTACTABILITY_1_PREV
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ALTER COLUMN HISTORY_DATE INTEGER NOT NULL;
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ALTER COLUMN PRODUCT_KEY INTEGER NOT NULL;
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ALTER COLUMN NEGOTIATOR_KEY INTEGER NOT NULL;
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ALTER COLUMN TOTAL_CALLS INTEGER NOT NULL;
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ALTER COLUMN SUCCESSFUL_CONTACTS INTEGER NOT NULL;

  ALTER TABLE DATA.CONTACTABILITY_1_PREV ADD CONSTRAINT FK_CONT1_HISTORY_DATE_PREV FOREIGN KEY (HISTORY_DATE)
    REFERENCES DATA.DIM_DATE(DATE_KEY);
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ADD CONSTRAINT FK_CONT1_PRODUCT_KEY_PREV FOREIGN KEY (PRODUCT_KEY)
    REFERENCES DATA.DIM_PRODUCT(PRODUCT_KEY);
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ADD CONSTRAINT FK_CONT1_NEGOTIATOR_KEY_PREV FOREIGN KEY (NEGOTIATOR_KEY)
    REFERENCES DATA.DIM_NEGOTIATOR(NEGOTIATOR_KEY);

  -- STEP 03: REPLACE SYNONYM DATA.CONTACTABILITY TO DATA.CONTACTABILITY_1_PREV
  DROP SYNONYM DATA.CONTACTABILITY;
  CREATE SYNONYM DATA.CONTACTABILITY FOR DATA.CONTACTABILITY_1_PREV;

  -- STEP 04: RENAME TABLE DATA.CONTACTABILITY_1 TO DATA.CONTACTABILITY_1_OLD
  EXEC sp_rename 'DATA.CONTACTABILITY_1', 'CONTACTABILITY_1_OLD';

  -- STEP 05: RENAME INDEXES AND CONSTRAINTS DATA.CONTACTABILITY_1_OLD
  EXEC sp_rename 'DATA.FK_CONT1_HISTORY_DATE', 'FK_CONT1_HISTORY_DATE_OLD';
  EXEC sp_rename 'DATA.FK_CONT1_PRODUCT_KEY', 'FK_CONT1_PRODUCT_KEY_OLD';
  EXEC sp_rename 'DATA.FK_CONT1_NEGOTIATOR_KEY', 'FK_CONT1_NEGOTIATOR_KEY_OLD';

  -- STEP 06: REPLACE SYNONYM DATA.CONTACTABILITY TO DATA.CONTACTABILITY_1_OLD
  DROP SYNONYM DATA.CONTACTABILITY;
  CREATE SYNONYM DATA.CONTACTABILITY FOR DATA.CONTACTABILITY_1_OLD;

  -- STEP 07: RENAME TABLE DATA.CONTACTABILITY_1_PREV TO DATA.CONTACTABILITY_1
  EXEC sp_rename 'DATA.CONTACTABILITY_1_PREV', 'CONTACTABILITY_1';

  -- STEP 08: RENAME INDEXES AND CONSTRAINTS DATA.CONTACTABILITY_1_PREV 
  EXEC sp_rename 'DATA.FK_CONT1_HISTORY_DATE_PREV', 'FK_CONT1_HISTORY_DATE';
  EXEC sp_rename 'DATA.FK_CONT1_PRODUCT_KEY_PREV', 'FK_CONT1_PRODUCT_KEY';
  EXEC sp_rename 'DATA.FK_CONT1_NEGOTIATOR_KEY_PREV', 'FK_CONT1_NEGOTIATOR_KEY';

  -- STEP 09: REPLACE SYNONYM DATA.CONTACTABILITY TO DATA.CONTACTABILITY_1
  DROP SYNONYM DATA.CONTACTABILITY;
  CREATE SYNONYM DATA.CONTACTABILITY FOR DATA.CONTACTABILITY_1;

  -- STEP 10: DROP OLD TABLE
  IF OBJECT_ID(N'[CIP_DM].[DATA].[CONTACTABILITY_1_OLD]',N'U') IS NOT NULL DROP TABLE CIP_DM.DATA.CONTACTABILITY_1_OLD;

  END TRY

  BEGIN CATCH

    DECLARE @ERROR_MESSAGE NVARCHAR(4000);
    DECLARE @ERROR_SEVERITY INT;
    DECLARE @ERROR_STATE INT;

    SELECT
      @ERROR_MESSAGE = ERROR_MESSAGE(),
      @ERROR_SEVERITY = ERROR_SEVERITY(),
      @ERROR_STATE = ERROR_STATE();

    RAISERROR (@ERROR_MESSAGE, @ERROR_SEVERITY, @ERROR_STATE);

  END CATCH

END;