CREATE PROCEDURE STAGE.SP_BUILD_DEBT_RECOVERY (@LOAD_DATE AS DATE) AS

BEGIN

  DECLARE @PERIOD AS CHAR(6);

  BEGIN TRY

  SELECT @PERIOD = LEFT(CONVERT(CHAR, @LOAD_DATE, 112), 6); /* YYYYMM */

  -- STEP 01: CREATE TABLE STAGE.TMP_DEBT_RECOVERY_01
  IF OBJECT_ID(N'[CIP_DM].[STAGE].[TMP_DEBT_RECOVERY_01]',N'U') IS NOT NULL DROP TABLE CIP_DM.STAGE.TMP_DEBT_RECOVERY_01;

  SELECT
    D1.PAYMENT_DATE,
    D1.PRODUCT_KEY,
    D1.NEGOTIATOR_KEY,
    D1.CURRENCY_KEY,
    D1.PAYMENTS,
    D1.AMOUNT_RECOVERED
  INTO STAGE.TMP_DEBT_RECOVERY_01
  FROM DATA.DEBT_RECOVERY_1 D1
  WHERE LEFT(D1.PAYMENT_DATE,6) <> @PERIOD; /* YYYYMM */

  -- STEP 02: CREATE TABLE STAGE.TMP_DEBT_RECOVERY_02
  IF OBJECT_ID(N'[CIP_DM].[STAGE].[TMP_DEBT_RECOVERY_02]',N'U') IS NOT NULL DROP TABLE CIP_DM.STAGE.TMP_DEBT_RECOVERY_02;

  SELECT
    P.PAYMENT_DATE,
    C.PRODUCT_KEY,
    H.NEGOTIATOR_KEY,
    P.CURRENCY_KEY,
    COUNT(P.AMOUNT) AS PAYMENTS,
    SUM(P.AMOUNT) AS AMOUNT_RECOVERED
  INTO STAGE.TMP_DEBT_RECOVERY_02
  FROM DATA.FACT_PAYMENT P
  LEFT JOIN DATA.HIST_ASSIGNMENT H
  ON LEFT(P.PAYMENT_DATE,6) = LEFT(H.DATE_KEY,6) AND P.CREDIT_KEY = H.CREDIT_KEY
   INNER JOIN DATA.DIM_CREDIT C
  ON C.CREDIT_KEY = H.CREDIT_KEY
  INNER JOIN DATA.DIM_PRODUCT O
  ON O.PRODUCT_KEY = C.PRODUCT_KEY
  WHERE LEFT(H.DATE_KEY,6) = @PERIOD
   GROUP BY C.PRODUCT_KEY,  H.NEGOTIATOR_KEY, P.PAYMENT_DATE, P.CURRENCY_KEY
   ORDER BY P.PAYMENT_DATE ASC;

  -- STEP 03: CREATE TABLE DATA.CONTACTABILITY_1_PREV
  IF OBJECT_ID(N'[CIP_DM].[DATA].[CONTACTABILITY_1_PREV]',N'U') IS NOT NULL DROP TABLE CIP_DM.DATA.CONTACTABILITY_1_PREV;

  SELECT
    PREV.PAYMENT_DATE,
    PREV.PRODUCT_KEY,
    PREV.NEGOTIATOR_KEY,
    PREV.CURRENCY_KEY,
    PREV.PAYMENTS,
    PREV.AMOUNT_RECOVERED
  INTO DATA.CONTACTABILITY_1_PREV FROM
  (
    SELECT
      D1.PAYMENT_DATE,
      D1.PRODUCT_KEY,
      D1.NEGOTIATOR_KEY,
      D1.CURRENCY_KEY,
      D1.PAYMENTS,
      D1.AMOUNT_RECOVERED
    FROM STAGE.TMP_DEBT_RECOVERY_01 D1
    UNION ALL
    SELECT
      D2.PAYMENT_DATE,
      D2.PRODUCT_KEY,
      D2.NEGOTIATOR_KEY,
      D2.CURRENCY_KEY,
      D2.PAYMENTS,
      D2.AMOUNT_RECOVERED
    FROM STAGE.TMP_DEBT_RECOVERY_02 D2
  ) PREV
  ORDER BY PAYMENT_DATE ASC;

  -- STEP 04: DROP TMP TABLAS
  IF OBJECT_ID('[CIP_DM].[STAGE].[TMP_DEBT_RECOVERY_01]') IS NOT NULL DROP TABLE CIP_DM.STAGE.TMP_DEBT_RECOVERY_01;
  IF OBJECT_ID('[CIP_DM].[STAGE].[TMP_DEBT_RECOVERY_02]') IS NOT NULL DROP TABLE CIP_DM.STAGE.TMP_DEBT_RECOVERY_02;

  -- STEP 05: CREATE INDEXES AND CONSTRAINTS DATA.CONTACTABILITY_1_PREV
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ALTER COLUMN PAYMENT_DATE INTEGER NOT NULL;
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ALTER COLUMN PRODUCT_KEY INTEGER NOT NULL;
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ALTER COLUMN NEGOTIATOR_KEY INTEGER NOT NULL;
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ALTER COLUMN CURRENCY_KEY CHAR(3) NOT NULL;
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ALTER COLUMN PAYMENTS INTEGER NOT NULL;
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ALTER COLUMN AMOUNT_RECOVERED DECIMAL(18,2) NOT NULL;

  ALTER TABLE DATA.CONTACTABILITY_1_PREV ADD CONSTRAINT FK_DEBTRECOVERY1_DATE_PREV FOREIGN KEY (PAYMENT_DATE)
    REFERENCES DATA.DIM_DATE(DATE_KEY);
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ADD CONSTRAINT FK_DEBTRECOVERY1_PRODUCT_PREV FOREIGN KEY (PRODUCT_KEY)
    REFERENCES DATA.DIM_PRODUCT(PRODUCT_KEY);
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ADD CONSTRAINT FK_DEBTRECOVERY1_NEGOTIATOR_PREV FOREIGN KEY (NEGOTIATOR_KEY)
    REFERENCES DATA.DIM_NEGOTIATOR(NEGOTIATOR_KEY);
  ALTER TABLE DATA.CONTACTABILITY_1_PREV ADD CONSTRAINT FK_DEBTRECOVERY1_CURRENCY_PREV FOREIGN KEY (CURRENCY_KEY)
    REFERENCES DATA.DIM_CURRENCY(CURRENCY_KEY);

  -- STEP 06: REPLACE SYNONYM DATA.DEBT_RECOVERY TO DATA.CONTACTABILITY_1_PREV
  DROP SYNONYM DATA.DEBT_RECOVERY;
  CREATE SYNONYM DATA.DEBT_RECOVERY FOR DATA.CONTACTABILITY_1_PREV;

  -- STEP 07: RENAME TABLE DATA.DEBT_RECOVERY_1 TO DATA.DEBT_RECOVERY_1_OLD
  EXEC sp_rename 'DATA.DEBT_RECOVERY_1', 'DEBT_RECOVERY_1_OLD';

  -- STEP 08: RENAME INDEXES AND CONSTRAINTS DATA.DEBT_RECOVERY_1_OLD
  EXEC sp_rename 'DATA.FK_DEBTRECOVERY1_DATE', 'FK_DEBTRECOVERY1_DATE_OLD';
  EXEC sp_rename 'DATA.FK_DEBTRECOVERY1_PRODUCT', 'FK_DEBTRECOVERY1_PRODUCT_OLD';
  EXEC sp_rename 'DATA.FK_DEBTRECOVERY1_NEGOTIATOR', 'FK_DEBTRECOVERY1_NEGOTIATOR_OLD';
  EXEC sp_rename 'DATA.FK_DEBTRECOVERY1_CURRENCY', 'FK_DEBTRECOVERY1_CURRENCY_OLD';

  -- STEP 09: REPLACE SYNONYM DATA.DEBT_RECOVERY TO DATA.DEBT_RECOVERY_1_OLD
  DROP SYNONYM DATA.DEBT_RECOVERY;
  CREATE SYNONYM DATA.DEBT_RECOVERY FOR DATA.DEBT_RECOVERY_1_OLD;

  -- STEP 10: RENAME TABLE DATA.CONTACTABILITY_1_PREV TO DATA.DEBT_RECOVERY_1
  EXEC sp_rename 'DATA.CONTACTABILITY_1_PREV', 'DEBT_RECOVERY_1';

  -- STEP 11: RENAME INDEXES AND CONSTRAINTS DATA.CONTACTABILITY_1_PREV 
  EXEC sp_rename 'DATA.FK_DEBTRECOVERY1_DATE_PREV', 'FK_DEBTRECOVERY1_DATE';
  EXEC sp_rename 'DATA.FK_DEBTRECOVERY1_PRODUCT_PREV', 'FK_DEBTRECOVERY1_PRODUCT';
  EXEC sp_rename 'DATA.FK_DEBTRECOVERY1_NEGOTIATOR_PREV', 'FK_DEBTRECOVERY1_NEGOTIATOR';
  EXEC sp_rename 'DATA.FK_DEBTRECOVERY1_CURRENCY_PREV', 'FK_DEBTRECOVERY1_CURRENCY';

  -- STEP 12: REPLACE SYNONYM DATA.DEBT_RECOVERY TO DATA.DEBT_RECOVERY_1
  DROP SYNONYM DATA.DEBT_RECOVERY;
  CREATE SYNONYM DATA.DEBT_RECOVERY FOR DATA.DEBT_RECOVERY_1;

  -- STEP 13: DROP OLD TABLE
  IF OBJECT_ID(N'[CIP_DM].[DATA].[DEBT_RECOVERY_1_OLD]',N'U') IS NOT NULL DROP TABLE CIP_DM.DATA.DEBT_RECOVERY_1_OLD;

  END TRY

  BEGIN CATCH

    DECLARE @ERROR_MESSAGE NVARCHAR(4000);
    DECLARE @ERROR_SEVERITY INT;
    DECLARE @ERROR_STATE INT;

    SELECT
      @ERROR_MESSAGE = ERROR_MESSAGE(),
      @ERROR_SEVERITY = ERROR_SEVERITY(),
      @ERROR_STATE = ERROR_STATE();

    RAISERROR (@ERROR_MESSAGE, @ERROR_SEVERITY, @ERROR_STATE);

  END CATCH

END;