CREATE PROCEDURE DATA.SP_LOAD_DIM_DATE (@START_DATE AS DATE, @END_DATE AS DATE) AS

BEGIN

  BEGIN TRY

  IF @END_DATE < @START_DATE
    BEGIN
     THROW 51000, 'End date must be greater than Start date.', 1;
    END

WHILE @START_DATE <= @END_DATE BEGIN
   EXEC DATA.SP_INSERT_DIM_DATE @START_DATE
   SET @START_DATE = DATEADD(DAY, 1, @START_DATE)
END

  END TRY

  BEGIN CATCH

    DECLARE @ERROR_MESSAGE NVARCHAR(4000);
    DECLARE @ERROR_SEVERITY INT;
    DECLARE @ERROR_STATE INT;

    SELECT
      @ERROR_MESSAGE = ERROR_MESSAGE(),
      @ERROR_SEVERITY = ERROR_SEVERITY(),
      @ERROR_STATE = ERROR_STATE();

    RAISERROR (@ERROR_MESSAGE, @ERROR_SEVERITY, @ERROR_STATE);

  END CATCH

END;