CREATE TABLE DATA.DIM_NEGOTIATOR (
  NEGOTIATOR_KEY INTEGER NOT NULL CONSTRAINT DF_DIMNEGOTIATOR_NEGOTIATORKEY DEFAULT (NEXT VALUE FOR DATA.SQ_I1_KEY_DIM_NEGOTIATOR),
  NEGOTIATOR_CODE VARCHAR(100),
  NEGOTIATOR_NAME NVARCHAR(255),
  CREATION_USER VARCHAR(100) NOT NULL CONSTRAINT DF_DIMNEGOTIATOR_CREATIONUSER DEFAULT CAST(SERVERPROPERTY('ServerName') AS NVARCHAR) + '-' + CAST(SERVERPROPERTY('MachineName') AS NVARCHAR),
  CREATION_DATE DATETIME  NOT NULL CONSTRAINT DF_DIMNEGOTIATOR_CREATIONDATE DEFAULT GETDATE(),
  CREATION_IP VARCHAR(50) NOT NULL CONSTRAINT DF_DIMNEGOTIATOR_CREATIONIP DEFAULT DBO.FN_GET_CURRENT_IP(),
  MODIFICATION_USER VARCHAR(100) NULL,
  MODIFICATION_DATE DATETIME NULL,
  MODIFICATION_IP VARCHAR(50) NULL,
  CONSTRAINT PK_DIM_NEGOTIATOR PRIMARY KEY (NEGOTIATOR_KEY)
);