CREATE VIEW DATA.VW_DEBT_COLLECTION AS
SELECT
  R.DATE_KEY,
  R.CREDIT_KEY,
  H.NEGOTIATOR_KEY,
  R.PAYMENTS_MADE,
  R.AMOUNT_RECOVERED
FROM DATA.HIST_ASSIGNMENT H
INNER JOIN (
SELECT
  P.DATE_KEY,
  P.CREDIT_KEY,
  COUNT(*) AS PAYMENTS_MADE,
  SUM(P.AMOUNT) AS AMOUNT_RECOVERED
FROM DATA.FACT_PAYMENT P
  GROUP BY P.DATE_KEY, P.CREDIT_KEY
) AS R
  ON LEFT(R.DATE_KEY,6) = H.PERIOD_CODE
    AND R.CREDIT_KEY = H.CREDIT_KEY;