CREATE VIEW DATA.VW_NEGOTIATOR_ASSIGNMENTS AS
SELECT
  H.PERIOD_CODE,
  H.NEGOTIATOR_KEY,
  COUNT(H.CREDIT_KEY) AS ASSIGNED_CREDITS,
  SUM(PRINCIPAL_AMNT) AS TOTAL_PRINCIPAL_AMNT,
  SUM(NET_DEBT_AMNT) AS TOTAL_NET_DEBT_AMNT
FROM DATA.HIST_ASSIGNMENT H
GROUP BY H.PERIOD_CODE, H.NEGOTIATOR_KEY;