CREATE VIEW DATA.VW_DEBT_RECOVERY AS
SELECT 
  H.PERIOD_CODE,
  H.NEGOTIATOR_KEY,
  H.CREDIT_KEY,
  P.DATE_KEY,
  P.AMOUNT
FROM DATA.HIST_ASSIGNMENT H
LEFT JOIN DATA.FACT_PAYMENT P
ON LEFT(P.DATE_KEY,6) = H.PERIOD_CODE
    AND P.CREDIT_KEY = H.CREDIT_KEY