CREATE TABLE DATA.DIM_CURRENCY (
  CURRENCY_KEY CHAR(3) NOT NULL, /* ISO 4217 */
  CURRENCY_NAME VARCHAR(255) NOT NULL,
  CREATION_USER VARCHAR(100) NOT NULL CONSTRAINT DF_DIMCURRENCY_CREATIONUSER DEFAULT CAST(SERVERPROPERTY('ServerName') AS NVARCHAR) + '-' + CAST(SERVERPROPERTY('MachineName') AS NVARCHAR),
  CREATION_DATE DATETIME  NOT NULL CONSTRAINT DF_DIMCURRENCY_CREATIONDATE DEFAULT GETDATE(),
  CREATION_IP VARCHAR(50) NOT NULL CONSTRAINT DF_DIMCURRENCY_CREATIONIP DEFAULT DBO.FN_GET_CURRENT_IP(),
  MODIFICATION_USER VARCHAR(100) NULL,
  MODIFICATION_DATE DATETIME NULL,
  MODIFICATION_IP VARCHAR(50) NULL
  CONSTRAINT PK_DIM_CURRENCY PRIMARY KEY (CURRENCY_KEY)
);