CREATE VIEW DATA.CREDIT_WITH_PAYMENTS AS
SELECT 
  H.PERIOD_CODE,
  H.CREDIT_KEY,
  H.NEGOTIATOR_KEY
FROM DATA.HIST_ASSIGNMENT H
WHERE EXISTS
  (
    SELECT
      1
    FROM DATA.FACT_PAYMENT P
    WHERE
      LEFT(P.DATE_KEY,6) = H.PERIOD_CODE AND P.CREDIT_KEY = H.CREDIT_KEY
  );