CREATE PROCEDURE DATA.SP_LOAD_DIM_NEGOTIATOR AS

BEGIN

  BEGIN TRY

    INSERT INTO DATA.DIM_NEGOTIATOR
      (
         NEGOTIATOR_CODE,
         NEGOTIATOR_NAME
      )
    SELECT
      *
     FROM (
            SELECT
              NEGOTIATOR_CODE,
              NEGOTIATOR_NAME
            FROM [STAGE].[HIST_ASSIGNMENT]
            GROUP BY NEGOTIATOR_CODE, NEGOTIATOR_NAME
    ) S
    WHERE NOT EXISTS
          (
            SELECT 1
            FROM DATA.DIM_NEGOTIATOR D
            WHERE D.NEGOTIATOR_CODE = S.NEGOTIATOR_CODE
          );

  END TRY

  BEGIN CATCH

    DECLARE @ERROR_MESSAGE NVARCHAR(4000);
    DECLARE @ERROR_SEVERITY INT;
    DECLARE @ERROR_STATE INT;

    SELECT
      @ERROR_MESSAGE = ERROR_MESSAGE(),
      @ERROR_SEVERITY = ERROR_SEVERITY(),
      @ERROR_STATE = ERROR_STATE();

    RAISERROR (@ERROR_MESSAGE, @ERROR_SEVERITY, @ERROR_STATE);

  END CATCH

END;