CREATE PROCEDURE STAGE.SP_LOAD_HIST_ASIGNACION (@FECHA_CARGA AS DATE) AS

BEGIN

  DECLARE @CREATION_USER AS VARCHAR(100);
  DECLARE @CREATION_DATE AS DATETIME;
  DECLARE @CREATION_IP AS VARCHAR(50);
  DECLARE @YYYYMM AS CHAR(6);

  BEGIN TRY

  SELECT @CREATION_USER = CAST(SERVERPROPERTY('ServerName') AS NVARCHAR) + '-' + CAST(SERVERPROPERTY('MachineName') AS NVARCHAR);
  SELECT @CREATION_DATE = GETDATE();
  SELECT @CREATION_IP = DBO.FN_GET_CURRENT_IP();

  SELECT @YYYYMM = LEFT(CONVERT(CHAR, @FECHA_CARGA, 112), 6);

  -- STEP 01: CREATE TABLE STAGE.TMP_HIST_ASIGNACION_01
  IF OBJECT_ID(N'[CIP_DM].[STAGE].[TMP_HIST_ASIGNACION_01]',N'U') IS NOT NULL DROP TABLE CIP_DM.STAGE.TMP_HIST_ASIGNACION_01;

    SELECT
      H1.CODIGO_PERIODO,
      H1.ID_CREDITO,
      H1.ID_GESTOR,
      H1.SALDO_CAPITAL_INICIAL,
      H1.DEUDA_TOTAL_INICIAL,
      H1.CREATION_USER,
      H1.CREATION_DATE,
      H1.CREATION_IP,
      H1.MODIFICATION_USER,
      H1.MODIFICATION_DATE,
      H1.MODIFICATION_IP
    INTO STAGE.TMP_HIST_ASIGNACION_01
    FROM DATA.HIST_ASIGNACION_1 H1
    WHERE H1.CODIGO_PERIODO <> @YYYYMM;

  -- STEP 02: CREATE TABLE STAGE.TMP_HIST_ASIGNACION_02
  IF OBJECT_ID(N'[CIP_DM].[STAGE].[TMP_HIST_ASIGNACION_02]',N'U') IS NOT NULL DROP TABLE CIP_DM.STAGE.TMP_HIST_ASIGNACION_02;

    SELECT
      @YYYYMM AS CODIGO_PERIODO,
      C.ID_CREDITO,
      G.ID_GESTOR,
      CAST(H.SALDO_CAPITAL_INICIAL AS DECIMAL(18,2)) AS SALDO_CAPITAL_INICIAL,
      CAST(H.DEUDA_TOTAL_INICIAL AS DECIMAL(18,2)) AS DEUDA_TOTAL_INICIAL,
      @CREATION_USER AS CREATION_USER,
      @CREATION_DATE AS CREATION_DATE,
      @CREATION_IP AS CREATION_IP,
      CAST(NULL AS VARCHAR(100)) AS MODIFICATION_USER,
      CAST(NULL AS DATETIME) AS MODIFICATION_DATE,
      CAST(NULL AS VARCHAR(50)) AS MODIFICATION_IP
    INTO STAGE.TMP_HIST_ASIGNACION_02
    FROM STAGE.HIST_ASIGNACION H
    LEFT JOIN DATA.DIM_CREDITO C ON C.CODIGO_CREDITO = H.CODIGO_CREDITO
    LEFT JOIN DATA.DIM_GESTOR G ON G.CODIGO_GESTOR = H.CODIGO_GESTOR;

  -- STEP 03: CREATE TABLE DATA.HIST_ASIGNACION_1_PREV
  IF OBJECT_ID(N'[CIP_DM].[DATA].[HIST_ASIGNACION_1_PREV]',N'U') IS NOT NULL DROP TABLE CIP_DM.DATA.HIST_ASIGNACION_1_PREV;

  SELECT
    PREV.CODIGO_PERIODO,
    PREV.ID_CREDITO,
    PREV.ID_GESTOR,
    PREV.SALDO_CAPITAL_INICIAL,
    PREV.DEUDA_TOTAL_INICIAL,
    PREV.CREATION_USER,
    PREV.CREATION_DATE,
    PREV.CREATION_IP,
    PREV.MODIFICATION_USER,
    PREV.MODIFICATION_DATE,
    PREV.MODIFICATION_IP
  INTO DATA.HIST_ASIGNACION_1_PREV FROM
  (SELECT
    H1.CODIGO_PERIODO,
    H1.ID_CREDITO,
    H1.ID_GESTOR,
    H1.SALDO_CAPITAL_INICIAL,
    H1.DEUDA_TOTAL_INICIAL,
    H1.CREATION_USER,
    H1.CREATION_DATE,
    H1.CREATION_IP,
    H1.MODIFICATION_USER,
    H1.MODIFICATION_DATE,
    H1.MODIFICATION_IP
  FROM STAGE.TMP_HIST_ASIGNACION_01 H1
  UNION
  SELECT
    H2.CODIGO_PERIODO,
    H2.ID_CREDITO,
    H2.ID_GESTOR,
    H2.SALDO_CAPITAL_INICIAL,
    H2.DEUDA_TOTAL_INICIAL,
    H2.CREATION_USER,
    H2.CREATION_DATE,
    H2.CREATION_IP,
    H2.MODIFICATION_USER,
    H2.MODIFICATION_DATE,
    H2.MODIFICATION_IP
  FROM STAGE.TMP_HIST_ASIGNACION_02 H2) PREV;

  -- STEP 04: DROP TMP TABLAS
  IF OBJECT_ID(N'[CIP_DM].[STAGE].[TMP_HIST_ASIGNACION_01]',N'U') IS NOT NULL DROP TABLE CIP_DM.STAGE.TMP_HIST_ASIGNACION_01;
  IF OBJECT_ID(N'[CIP_DM].[STAGE].[TMP_HIST_ASIGNACION_02]',N'U') IS NOT NULL DROP TABLE CIP_DM.STAGE.TMP_HIST_ASIGNACION_02;

  -- STEP 05: CREATE INDEXES AND CONSTRAINTS DATA.HIST_ASIGNACION_1_PREV
  ALTER TABLE DATA.HIST_ASIGNACION_1_PREV ALTER COLUMN CODIGO_PERIODO INTEGER NOT NULL;
  ALTER TABLE DATA.HIST_ASIGNACION_1_PREV ALTER COLUMN ID_CREDITO INTEGER NOT NULL;
  ALTER TABLE DATA.HIST_ASIGNACION_1_PREV ALTER COLUMN ID_GESTOR INTEGER NOT NULL;
  ALTER TABLE DATA.HIST_ASIGNACION_1_PREV ADD CONSTRAINT FK_ASIGNACION1_CREDITO_PREV FOREIGN KEY (ID_CREDITO)
    REFERENCES DATA.DIM_CREDITO(ID_CREDITO);
  ALTER TABLE DATA.HIST_ASIGNACION_1_PREV ADD CONSTRAINT FK_ASIGNACION1_GESTOR_PREV FOREIGN KEY (ID_GESTOR)
    REFERENCES DATA.DIM_GESTOR(ID_GESTOR);
  ALTER TABLE DATA.HIST_ASIGNACION_1_PREV ADD CONSTRAINT PK_HIST_ASIGNACION_1_PREV UNIQUE (CODIGO_PERIODO,ID_CREDITO);

  -- STEP 06: REPLACE SYNONYM DATA.HIST_ASIGNACION TO DATA.HIST_ASIGNACION_1_PREV
  DROP SYNONYM DATA.HIST_ASIGNACION;
  CREATE SYNONYM DATA.HIST_ASIGNACION FOR DATA.HIST_ASIGNACION_1_PREV;

  -- STEP 07: RENAME TABLE DATA.HIST_ASIGNACION_1 TO DATA.HIST_ASIGNACION_1_OLD
  EXEC sp_rename 'DATA.HIST_ASIGNACION_1', 'HIST_ASIGNACION_1_OLD';

  -- STEP 08: RENAME INDEXES AND CONSTRAINTS DATA.HIST_ASIGNACION_1_OLD
  EXEC sp_rename 'DATA.FK_ASIGNACION1_CREDITO', 'FK_ASIGNACION1_CREDITO_OLD';
  EXEC sp_rename 'DATA.FK_ASIGNACION1_GESTOR', 'FK_ASIGNACION1_GESTOR_OLD';
  EXEC sp_rename 'DATA.PK_HIST_ASIGNACION_1', 'PK_HIST_ASIGNACION_1_OLD';

  -- STEP 09: REPLACE SYNONYM DATA.HIST_ASIGNACION TO DATA.HIST_ASIGNACION_1_OLD
  DROP SYNONYM DATA.HIST_ASIGNACION;
  CREATE SYNONYM DATA.HIST_ASIGNACION FOR DATA.HIST_ASIGNACION_1_OLD;

  -- STEP 10: RENAME TABLE DATA.HIST_ASIGNACION_1_PREV TO DATA.HIST_ASIGNACION_1
  EXEC sp_rename 'DATA.HIST_ASIGNACION_1_PREV', 'HIST_ASIGNACION_1';

  -- STEP 11: RENAME INDEXES AND CONSTRAINTS DATA.HIST_ASIGNACION_1_PREV 
  EXEC sp_rename 'DATA.FK_ASIGNACION1_CREDITO_PREV', 'FK_ASIGNACION1_CREDITO';
  EXEC sp_rename 'DATA.FK_ASIGNACION1_GESTOR_PREV', 'FK_ASIGNACION1_GESTOR';
  EXEC sp_rename 'DATA.PK_HIST_ASIGNACION_1_PREV', 'PK_HIST_ASIGNACION_1';

  -- STEP 12: REPLACE SYNONYM DATA.HIST_ASIGNACION TO DATA.HIST_ASIGNACION_1
  DROP SYNONYM DATA.HIST_ASIGNACION;
  CREATE SYNONYM DATA.HIST_ASIGNACION FOR DATA.HIST_ASIGNACION_1;

  -- STEP 10: DROP OLD TABLE
  IF OBJECT_ID(N'[CIP_DM].[DATA].[HIST_ASIGNACION_1_OLD]',N'U') IS NOT NULL DROP TABLE CIP_DM.DATA.HIST_ASIGNACION_1_OLD;

  -- STEP 11: ADD DEFAULT CONSTRAINTS
  ALTER TABLE DATA.HIST_ASIGNACION_1 ADD CONSTRAINT DF_HISTASIGNACION1_CREATIONUSER
    DEFAULT CAST(SERVERPROPERTY('ServerName') AS NVARCHAR) + '-' + CAST(SERVERPROPERTY('MachineName') AS NVARCHAR)
      FOR CREATION_USER;
  ALTER TABLE DATA.HIST_ASIGNACION_1 ADD CONSTRAINT DF_HISTASIGNACION1_CREATIONDATE DEFAULT GETDATE()
      FOR CREATION_DATE;
  ALTER TABLE DATA.HIST_ASIGNACION_1 ADD CONSTRAINT DF_HISTASIGNACION1_CREATIONIP DEFAULT DBO.FN_GET_CURRENT_IP()
      FOR CREATION_IP;

  END TRY

  BEGIN CATCH

    DECLARE @ERROR_MESSAGE NVARCHAR(4000);
    DECLARE @ERROR_SEVERITY INT;
    DECLARE @ERROR_STATE INT;

    SELECT
      @ERROR_MESSAGE = ERROR_MESSAGE(),
      @ERROR_SEVERITY = ERROR_SEVERITY(),
      @ERROR_STATE = ERROR_STATE();

    RAISERROR (@ERROR_MESSAGE, @ERROR_SEVERITY, @ERROR_STATE);

  END CATCH

END;