CREATE TABLE DATA.DIM_PRODUCT (
  PRODUCT_KEY INTEGER NOT NULL CONSTRAINT DF_DIMPRODUCT_PRODUCTKEY DEFAULT (NEXT VALUE FOR DATA.SQ_I1_KEY_DIM_PRODUCT),
  PRODUCT_NAME NVARCHAR(255),
  CREATION_USER VARCHAR(100) NOT NULL CONSTRAINT DF_DIMPRODUCT_CREATIONUSER DEFAULT CAST(SERVERPROPERTY('ServerName') AS NVARCHAR) + '-' + CAST(SERVERPROPERTY('MachineName') AS NVARCHAR),
  CREATION_DATE DATETIME NOT NULL CONSTRAINT DF_DIMPRODUCT_CREATIONDATE DEFAULT GETDATE(),
  CREATION_IP VARCHAR(50) NOT NULL CONSTRAINT DF_DIMPRODUCT_CREATIONIP DEFAULT DBO.FN_GET_CURRENT_IP(),
  MODIFICATION_USER VARCHAR(100) NULL,
  MODIFICATION_DATE DATETIME NULL,
  MODIFICATION_IP VARCHAR(50) NULL,
  CONSTRAINT PK_DIM_PRODUCT PRIMARY KEY (PRODUCT_KEY),
  CONSTRAINT UQ_DIMPRODUCT_PRODUCTNAME UNIQUE (PRODUCT_NAME)
);