CREATE TABLE DATA.FACT_PAGOS_1 (
  ID_CREDITO INTEGER NOT NULL,
  ID_FECHA INTEGER NOT NULL,
  MONTO DECIMAL(18,2) NOT NULL,
  MONEDA CHAR(3) NOT NULL,
  AGENCIA VARCHAR(255) NULL,
  CREATION_USER VARCHAR(100) NOT NULL CONSTRAINT DF_FACTPAGOS1_CREATIONUSER DEFAULT CAST(SERVERPROPERTY('ServerName') AS NVARCHAR) + '-' + CAST(SERVERPROPERTY('MachineName') AS NVARCHAR),
  CREATION_DATE DATETIME NOT NULL CONSTRAINT DF_FACTPAGOS1_CREATIONDATE DEFAULT GETDATE(),
  CREATION_IP VARCHAR(50) NOT NULL CONSTRAINT DF_FACTPAGOS1_CREATIONIP DEFAULT DBO.FN_GET_CURRENT_IP(),
  MODIFICATION_USER VARCHAR(100) NULL,
  MODIFICATION_DATE DATETIME NULL,
  MODIFICATION_IP VARCHAR(50) NULL,
  CONSTRAINT FK_PAGOS1_CREDITO FOREIGN KEY (ID_CREDITO)
    REFERENCES DATA.DIM_CREDITO(ID_CREDITO),
  CONSTRAINT FK_PAGOS1_FECHA FOREIGN KEY (ID_FECHA)
    REFERENCES DATA.DIM_FECHA(ID_FECHA)
);