CREATE TABLE DATA.DIM_GESTOR (
  ID_GESTOR INTEGER NOT NULL CONSTRAINT DF_DIMGESTOR_IDGESTOR DEFAULT (NEXT VALUE FOR DATA.SQ_I1_ID_DIM_GESTOR),
  CODIGO_GESTOR VARCHAR(100),
  NOMBRE_GESTOR NVARCHAR(255),
  CREATION_USER VARCHAR(100) NOT NULL CONSTRAINT DF_DIMGESTOR_CREATIONUSER DEFAULT CAST(SERVERPROPERTY('ServerName') AS NVARCHAR) + '-' + CAST(SERVERPROPERTY('MachineName') AS NVARCHAR),
  CREATION_DATE DATETIME  NOT NULL CONSTRAINT DF_DIMGESTOR_CREATIONDATE DEFAULT GETDATE(),
  CREATION_IP VARCHAR(50) NOT NULL CONSTRAINT DF_DIMGESTOR_CREATIONIP DEFAULT DBO.FN_GET_CURRENT_IP(),
  MODIFICATION_USER VARCHAR(100) NULL,
  MODIFICATION_DATE DATETIME NULL,
  MODIFICATION_IP VARCHAR(50) NULL,
  CONSTRAINT PK_DIM_GESTOR PRIMARY KEY (ID_GESTOR)
);