CREATE TABLE DATA.HIST_ASIGNACION_1 (
  CODIGO_PERIODO INTEGER NOT NULL, /* FORMAT YYYYMM */
  ID_CREDITO INTEGER NOT NULL,
  ID_GESTOR INTEGER NOT NULL,
  SALDO_CAPITAL_INICIAL DECIMAL(18,2),
  DEUDA_TOTAL_INICIAL DECIMAL(18,2),
  CREATION_USER VARCHAR(100) NOT NULL CONSTRAINT DF_HISTASIGNACION1_CREATIONUSER DEFAULT CAST(SERVERPROPERTY('ServerName') AS NVARCHAR) + '-' + CAST(SERVERPROPERTY('MachineName') AS NVARCHAR),
  CREATION_DATE DATETIME  NOT NULL CONSTRAINT DF_HISTASIGNACION1_CREATIONDATE DEFAULT GETDATE(),
  CREATION_IP VARCHAR(50) NOT NULL CONSTRAINT DF_HISTASIGNACION1_CREATIONIP DEFAULT DBO.FN_GET_CURRENT_IP(),
  MODIFICATION_USER VARCHAR(100) NULL,
  MODIFICATION_DATE DATETIME NULL,
  MODIFICATION_IP VARCHAR(50) NULL,
  CONSTRAINT FK_ASIGNACION1_CREDITO FOREIGN KEY (ID_CREDITO)
    REFERENCES DATA.DIM_CREDITO(ID_CREDITO),
  CONSTRAINT FK_ASIGNACION1_GESTOR FOREIGN KEY (ID_GESTOR)
    REFERENCES DATA.DIM_GESTOR(ID_GESTOR),
  CONSTRAINT PK_HIST_ASIGNACION_1 PRIMARY KEY (CODIGO_PERIODO,ID_CREDITO)
);