CREATE PROCEDURE DATA.SP_LOAD_DIM_CREDIT AS

BEGIN

  BEGIN TRY

    INSERT INTO DATA.DIM_CREDIT
      (
        CREDIT_CODE,
        CLIENT_CODE,
        CLIENT_DOCN,
        CLIENT_NAME
      )
    SELECT
        S.CREDIT_CODE,
        S.CLIENT_CODE,
        S.CLIENT_DOCN,
        S.CLIENT_NAME
    FROM STAGE.DIM_CREDIT S
    WHERE NOT EXISTS
          (
            SELECT 1
            FROM DATA.DIM_CREDIT D
            WHERE D.CREDIT_CODE = S.CREDIT_CODE
          );

  END TRY

  BEGIN CATCH

    DECLARE @ERROR_MESSAGE NVARCHAR(4000);
    DECLARE @ERROR_SEVERITY INT;
    DECLARE @ERROR_STATE INT;

    SELECT
      @ERROR_MESSAGE = ERROR_MESSAGE(),
      @ERROR_SEVERITY = ERROR_SEVERITY(),
      @ERROR_STATE = ERROR_STATE();

    RAISERROR (@ERROR_MESSAGE, @ERROR_SEVERITY, @ERROR_STATE);

  END CATCH

END;