CREATE PROCEDURE DATA.SP_LOAD_DIM_RESPONSE AS

BEGIN

  BEGIN TRY

    INSERT INTO DATA.DIM_RESPONSE
      (
        RESPONSE_NAME,
        FLAG
      )
    SELECT
        S.RESPONSE_NAME,
        S.FLAG
    FROM STAGE.DIM_RESPONSE S
    WHERE NOT EXISTS
          (
            SELECT 1
            FROM DATA.DIM_RESPONSE A
            WHERE A.RESPONSE_NAME = S.RESPONSE_NAME
          );

  END TRY

  BEGIN CATCH

    DECLARE @ERROR_MESSAGE NVARCHAR(4000);
    DECLARE @ERROR_SEVERITY INT;
    DECLARE @ERROR_STATE INT;

    SELECT
      @ERROR_MESSAGE = ERROR_MESSAGE(),
      @ERROR_SEVERITY = ERROR_SEVERITY(),
      @ERROR_STATE = ERROR_STATE();

    RAISERROR (@ERROR_MESSAGE, @ERROR_SEVERITY, @ERROR_STATE);

  END CATCH

END;