-- CREATE TABLE
CREATE TABLE DATA.DIM_RESPONSE (
  RESPONSE_KEY INTEGER NOT NULL CONSTRAINT DF_DIMRESPONSE_RESPONSEKEY DEFAULT (NEXT VALUE FOR DATA.SQ_I1_KEY_DIM_RESPONSE),
  RESPONSE_NAME VARCHAR(255) NOT NULL,
  FLAG CHAR(1),
  CREATION_USER VARCHAR(100) NOT NULL CONSTRAINT DF_DIMRESPONSE_CREATIONUSER DEFAULT CAST(SERVERPROPERTY('SERVERNAME') AS NVARCHAR) + '-' + CAST(SERVERPROPERTY('MACHINENAME') AS NVARCHAR),
  CREATION_DATE DATETIME NOT NULL CONSTRAINT DF_DIMRESPONSE_CREATIONDATE DEFAULT GETDATE(),
  CREATION_IP VARCHAR(50) NOT NULL CONSTRAINT DF_DIMRESPONSE_CREATIONIP DEFAULT DBO.FN_GET_CURRENT_IP(),
  MODIFICATION_USER VARCHAR(100) NULL,
  MODIFICATION_DATE DATETIME NULL,
  MODIFICATION_IP VARCHAR(50) NULL
  CONSTRAINT PK_DIM_RESPONSE PRIMARY KEY (RESPONSE_KEY),
  CONSTRAINT UQ_DIMRESPONSE_RESPONSENAME UNIQUE(RESPONSE_NAME)
);