CREATE PROCEDURE DATA.SP_INSERT_DIM_CREDITO AS

BEGIN

  BEGIN TRY

    INSERT INTO DATA.DIM_CREDITO
      (
        CODIGO_CREDITO,
        CODIGO_CLIENTE,
        DOCNUM_CLIENTE,
        NOMBRE_CLIENTE
      )
    SELECT
        S.CODIGO_CREDITO,
        S.CODIGO_CLIENTE,
        S.DOCNUM_CLIENTE,
        S.NOMBRE_CLIENTE
    FROM STAGE.DIM_CREDITO S
    WHERE NOT EXISTS
          (
            SELECT 1
            FROM DATA.DIM_CREDITO D
            WHERE D.CODIGO_CREDITO = S.CODIGO_CREDITO
          );

  END TRY

  BEGIN CATCH

    DECLARE @ERROR_MESSAGE NVARCHAR(4000);
    DECLARE @ERROR_SEVERITY INT;
    DECLARE @ERROR_STATE INT;

    SELECT
      @ERROR_MESSAGE = ERROR_MESSAGE(),
      @ERROR_SEVERITY = ERROR_SEVERITY(),
      @ERROR_STATE = ERROR_STATE();

    RAISERROR (@ERROR_MESSAGE, @ERROR_SEVERITY, @ERROR_STATE);

  END CATCH

END;