CREATE PROCEDURE DATA.SP_INSERT_DIM_GESTOR AS

BEGIN

  BEGIN TRY

    INSERT INTO DATA.DIM_GESTOR
      (
         CODIGO_GESTOR,
         NOMBRE_GESTOR
      )
    SELECT
        S.CODIGO_GESTOR,
        S.NOMBRE_GESTOR
    FROM STAGE.DIM_GESTOR S
    WHERE NOT EXISTS
          (
            SELECT 1
            FROM DATA.DIM_GESTOR D
            WHERE D.CODIGO_GESTOR = S.CODIGO_GESTOR
          );

  END TRY

  BEGIN CATCH

    DECLARE @ERROR_MESSAGE NVARCHAR(4000);
    DECLARE @ERROR_SEVERITY INT;
    DECLARE @ERROR_STATE INT;

    SELECT
      @ERROR_MESSAGE = ERROR_MESSAGE(),
      @ERROR_SEVERITY = ERROR_SEVERITY(),
      @ERROR_STATE = ERROR_STATE();

    RAISERROR (@ERROR_MESSAGE, @ERROR_SEVERITY, @ERROR_STATE);

  END CATCH

END;