-- CREATE TABLE
CREATE TABLE DATA.DIM_ACTION (
  ACTION_KEY INTEGER NOT NULL CONSTRAINT DF_DIMACTION_ACTIONKEY DEFAULT (NEXT VALUE FOR DATA.SQ_I1_KEY_DIM_ACTION),
  ACTION_NAME VARCHAR(255) NOT NULL,
  FLAG CHAR(1),
  CREATION_USER VARCHAR(100) NOT NULL CONSTRAINT DF_DIMACTION_CREATIONUSER DEFAULT CAST(SERVERPROPERTY('ServerName') AS NVARCHAR) + '-' + CAST(SERVERPROPERTY('MachineName') AS NVARCHAR),
  CREATION_DATE DATETIME NOT NULL CONSTRAINT DF_DIMACTION_CREATIONDATE DEFAULT GETDATE(),
  CREATION_IP VARCHAR(50) NOT NULL CONSTRAINT DF_DIMACTION_CREATIONIP DEFAULT DBO.FN_GET_CURRENT_IP(),
  MODIFICATION_USER VARCHAR(100) NULL,
  MODIFICATION_DATE DATETIME NULL,
  MODIFICATION_IP VARCHAR(50) NULL
  CONSTRAINT PK_DIM_ACTION PRIMARY KEY (ACTION_KEY),
  CONSTRAINT UQ_DIMACTION_ACTIONNAME UNIQUE (ACTION_NAME)
);