CREATE PROCEDURE DATA.SP_LOAD_DIM_PRODUCT AS

BEGIN

  BEGIN TRY

    INSERT INTO DATA.DIM_PRODUCT
      (
         PRODUCT_NAME
      )
    SELECT
      *
     FROM (
            SELECT
              PRODUCT_NAME
            FROM [STAGE].[HIST_ASSIGNMENT]
            GROUP BY PRODUCT_NAME
    ) S
    WHERE NOT EXISTS
          (
            SELECT 1
            FROM DATA.DIM_PRODUCT D
            WHERE D.PRODUCT_NAME = S.PRODUCT_NAME
          );

  END TRY

  BEGIN CATCH

    DECLARE @ERROR_MESSAGE NVARCHAR(4000);
    DECLARE @ERROR_SEVERITY INT;
    DECLARE @ERROR_STATE INT;

    SELECT
      @ERROR_MESSAGE = ERROR_MESSAGE(),
      @ERROR_SEVERITY = ERROR_SEVERITY(),
      @ERROR_STATE = ERROR_STATE();

    RAISERROR (@ERROR_MESSAGE, @ERROR_SEVERITY, @ERROR_STATE);

  END CATCH

END;