CREATE VIEW DATA.VW_RECUPERACION_CARTERA AS
SELECT
  R.ID_FECHA,
  R.ID_CREDITO,
  H.ID_GESTOR,
  R.PAGOS_EFECTUADOS,
  R.MONTO_RECUPERADO
FROM DATA.HIST_ASIGNACION H
INNER JOIN (
SELECT
  P.ID_FECHA,
  P.ID_CREDITO,
  COUNT(*) AS PAGOS_EFECTUADOS,
  SUM(P.MONTO) AS MONTO_RECUPERADO
FROM DATA.FACT_PAGOS P
  GROUP BY P.ID_FECHA, P.ID_CREDITO
) AS R
  ON LEFT(R.ID_FECHA,6) = H.CODIGO_PERIODO
    AND R.ID_CREDITO = H.ID_CREDITO;