CREATE TABLE DATA.DIM_CREDITO (
  ID_CREDITO INTEGER NOT NULL CONSTRAINT DF_DIMCREDITO_IDCREDITO DEFAULT (NEXT VALUE FOR DATA.SQ_I1_ID_DIM_CREDITO),
  CODIGO_CREDITO VARCHAR(100),
  CODIGO_CLIENTE VARCHAR(100),
  DOCNUM_CLIENTE VARCHAR(50),
  NOMBRE_CLIENTE NVARCHAR(255),
  CREATION_USER VARCHAR(100) NOT NULL CONSTRAINT DF_DIMCREDITO_CREATIONUSER DEFAULT CAST(SERVERPROPERTY('ServerName') AS NVARCHAR) + '-' + CAST(SERVERPROPERTY('MachineName') AS NVARCHAR),
  CREATION_DATE DATETIME NOT NULL CONSTRAINT DF_DIMCREDITO_CREATIONDATE DEFAULT GETDATE(),
  CREATION_IP VARCHAR(50) NOT NULL CONSTRAINT DF_DIMCREDITO_CREATIONIP DEFAULT DBO.FN_GET_CURRENT_IP(),
  MODIFICATION_USER VARCHAR(100) NULL,
  MODIFICATION_DATE DATETIME NULL,
  MODIFICATION_IP VARCHAR(50) NULL,
  CONSTRAINT PK_DIM_CREDITO PRIMARY KEY (ID_CREDITO)
);