-- CREATE TABLE
CREATE TABLE DATA.DIM_CONTACT (
  CONTACT_KEY INTEGER NOT NULL CONSTRAINT DF_DIMCONTACT_CONTACTKEY DEFAULT (NEXT VALUE FOR DATA.SQ_I1_KEY_DIM_CONTACT),
  CONTACT_NAME VARCHAR(255) NOT NULL,
  FLAG CHAR(1),
  CREATION_USER VARCHAR(100) NOT NULL CONSTRAINT DF_DIMCONTACT_CREATIONUSER DEFAULT CAST(SERVERPROPERTY('ServerName') AS NVARCHAR) + '-' + CAST(SERVERPROPERTY('MachineName') AS NVARCHAR),
  CREATION_DATE DATETIME NOT NULL CONSTRAINT DF_DIMCONTACT_CREATIONDATE DEFAULT GETDATE(),
  CREATION_IP VARCHAR(50) NOT NULL CONSTRAINT DF_DIMCONTACT_CREATIONIP DEFAULT DBO.FN_GET_CURRENT_IP(),
  MODIFICATION_USER VARCHAR(100) NULL,
  MODIFICATION_DATE DATETIME NULL,
  MODIFICATION_IP VARCHAR(50) NULL
  CONSTRAINT PK_DIM_CONTACT PRIMARY KEY (CONTACT_KEY),
  CONSTRAINT UQ_DIMCONTACT_CONTACTNAME UNIQUE (CONTACT_NAME)
);