CREATE PROCEDURE DATA.SP_LOAD_DIM_CONTACT AS

BEGIN

  BEGIN TRY

    INSERT INTO DATA.DIM_CONTACT
      (
        CONTACT_NAME,
        FLAG
      )
    SELECT
        S.CONTACT_NAME,
        S.FLAG
    FROM STAGE.DIM_CONTACT S
    WHERE NOT EXISTS
          (
            SELECT 1
            FROM DATA.DIM_CONTACT A
            WHERE A.CONTACT_NAME = S.CONTACT_NAME
          );

  END TRY

  BEGIN CATCH

    DECLARE @ERROR_MESSAGE NVARCHAR(4000);
    DECLARE @ERROR_SEVERITY INT;
    DECLARE @ERROR_STATE INT;

    SELECT
      @ERROR_MESSAGE = ERROR_MESSAGE(),
      @ERROR_SEVERITY = ERROR_SEVERITY(),
      @ERROR_STATE = ERROR_STATE();

    RAISERROR (@ERROR_MESSAGE, @ERROR_SEVERITY, @ERROR_STATE);

  END CATCH

END;