CREATE TABLE STAGE.HIST_ASSIGNMENT (
  CREDIT_CODE VARCHAR(100),
  CLIENT_CODE VARCHAR(100),
  CLIENT_DOCN VARCHAR(50),
  CLIENT_NAME VARCHAR(255),
  PORTFOLIO_NAME VARCHAR(255),
  PRODUCT_NAME VARCHAR(255),
  PRINCIPAL_AMNT VARCHAR(20),
  NET_DEBT_AMNT VARCHAR(20),
  NEGOTIATOR_CODE VARCHAR(100),
  NEGOTIATOR_NAME VARCHAR(255)
);