-- CARTERA_COMPARTAMOS_202012
--CREATE VIEW DATA.CARTERA_COMPARTAMOS_202012 AS 
SELECT DISTINCT
  C.ACCOUNT_CODE AS CREDIT_CODE,
  C.CLIENT_CODE,
  C.CLIENT_DOCN,
  C.CLIENT_NAME,
  C.PORTFOLIO_NAME,
  C.PRODUCT_NAME,
  C.PRINCIPAL_AMNT,
  C.NET_DEBT_AMNT,
  N.NEGOTIATOR_CODE,
  C.NEGOTIATOR_NAME
FROM DATA.DIM_CREDIT_1 C
LEFT JOIN DATA.DIM_NEGOTIATOR N ON N.NEGOTIATOR_NAME = C.NEGOTIATOR_NAME
LEFT JOIN DATA.FACT_NEGOTATION F ON C.CREDIT_ID = F.CREDIT_ID
LEFT JOIN VW_PAGOS_COMPARTAMOS P ON P.CREDIT_CODE = C.account_code
WHERE
C.PORTFOLIO_NAME = 'COMPARTAMOS' AND N.NEGOTIATOR_NAME <> 'OFICINA' AND
(
F.HISTORY_DATE BETWEEN '2020-07-01' AND '2020-07-31'
OR P.PAYMENT_DATE BETWEEN '2020-07-01' AND '2020-07-31'
)
UNION
SELECT DISTINCT
  C.ACCOUNT_CODE AS CREDIT_CODE,
  C.CLIENT_CODE,
  C.CLIENT_DOCN,
  C.CLIENT_NAME,
  C.PORTFOLIO_NAME,
  C.PRODUCT_NAME,
  C.PRINCIPAL_AMNT,
  C.NET_DEBT_AMNT,
  N.NEGOTIATOR_CODE,
  N.NEGOTIATOR_NAME
FROM DATA.DIM_CREDIT_1 C
INNER JOIN DATA.DIM_NEGOTIATOR N ON N.NEGOTIATOR_NAME = C.NEGOTIATOR_NAME
WHERE
C.PORTFOLIO_NAME = 'COMPARTAMOS' AND N.NEGOTIATOR_NAME <> 'OFICINA' AND
CONVERT(DATE,C.CREATION_DATE,23) BETWEEN '2020-07-01' AND '2020-07-31';





SELECT 
  C.ACCOUNT_CODE AS CREDIT_CODE,
  C.CLIENT_CODE,
  C.CLIENT_DOCN,
  C.CLIENT_NAME,
  C.PORTFOLIO_NAME,
  C.PRODUCT_NAME,
  C.PRINCIPAL_AMNT,
  C.NET_DEBT_AMNT,
  N.NEGOTIATOR_CODE,
  C.NEGOTIATOR_NAME
FROM DATA.DIM_CREDIT_1 C
LEFT JOIN DATA.DIM_NEGOTIATOR N ON N.NEGOTIATOR_NAME = C.NEGOTIATOR_NAME
WHERE C.account_code = '062310352307';


SELECT NEGOTIATOR_NAME FROM  DATA.DIM_NEGOTIATOR N 
GROUP BY NEGOTIATOR_NAME;



SELECT c.*, g.gest_nom , u.nombre from  [SEGURO02_09].[dbo].[cob_cuentas1] C 
INNER JOIN [SEGURO02_09].[dbo].exl_gestor G ON G.cod_gestor = C.cod_gestor
INNER JOIN [SEGURO02_09].[dbo].cob_mae_usuario u ON u.codusuario = g.codusuario
WHERE C.cod_cta = '062310352307';

SELECT PRODUCT_NAME FROM DATA.DIM_CREDIT_1 WHERE
PORTFOLIO_NAME = 'COMPARTAMOS'
AND CONVERT(DATE,CREATION_DATE,23) >= '2020-01-01'
GROUP BY PRODUCT_NAME;

-- GESTIONES_COMPARTAMOS_202012
SELECT * FROM GESTIONES_COMPARTAMOS_202012;

--CREATE VIEW  GESTIONES_COMPARTAMOS_202012 AS
SELECT DISTINCT
    C.ACCOUNT_CODE AS CREDIT_CODE,
    A.ACTION_NAME,
    RP.RESPONSE_NAME,
    CASE WHEN  CO.CONTACT_NAME = '' AND  RP.RESPONSE_NAME = 'CONTACTO DIRECTO' THEN 'ENCARGADO' ELSE CO.CONTACT_NAME END AS CONTACT_NAME,
    ---CAST(F.REASON_ID AS INTEGER) AS REASON_ID,
    N.NEGOTIATOR_CODE,
    E.CARRIER_NAME,
    CONVERT(DATE, F.HISTORY_DATE, 23) AS HISTORY_DATE,
	REPLACE(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(UPPER(F.OBSERVATION))),CHAR(9),''), CHAR(13), ''), CHAR(10), ''),'"','') AS OBSERVATION,
    F.TELEPHONE_NUMBER,
    REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(UPPER(F.TELEPHONE_STATUS))),CHAR(9),''), CHAR(13), ''), CHAR(10), '') AS TELEPHONE_STATUS,
    CONVERT(DECIMAL(15,2), F.PROMISE_AMNT) AS PROMISE_AMNT,
    CONVERT(DATE, F.PROMISE_NEXT_DATE, 23) AS PROMISE_NEXT_DATE,
    F.FLAG
  FROM STAGE.FACT_NEGOTATION F
  INNER JOIN DATA.DIM_CREDIT_1 C ON C.CREDIT_ID = F.CREDIT_ID
  INNER JOIN DATA.DIM_NEGOTIATOR N ON N.NEGOTIATOR_ID = F.NEGOTIATOR_ID
  INNER JOIN DATA.CARTERA_COMPARTAMOS_202012 O ON (N.NEGOTIATOR_CODE = O.NEGOTIATOR_CODE AND O.CREDIT_CODE = C.ACCOUNT_CODE)
  INNER JOIN DATA.DIM_ACTION A ON A.ACTION_ID = F.ACTION_ID
  INNER JOIN DATA.DIM_RESPONSE RP ON RP.RESPONSE_ID = F.RESPONSE_ID
  INNER JOIN DATA.DIM_CONTACT CO ON CO.CONTACT_ID = F.CONTACT_ID
  LEFT JOIN DATA.DIM_CARRIER E ON E.CARRIER_ID = F.CARRIER_ID
  WHERE F.HISTORY_DATE BETWEEN '2020-07-01' AND '2020-07-31'
  AND C.PORTFOLIO_NAME = 'COMPARTAMOS' AND C.NEGOTIATOR_NAME <> 'OFICINA';
 -- AND CONVERT(DATE,C.CREATION_DATE,23) BETWEEN '2020-01-01' AND  '2020-01-30'
 -- ORDER BY F.HISTORY_DATE ASC;


  -- DIMENSIONES
  SELECT ACTION_NAME , FLAG FROM DATA.dim_action;

SELECT  distinct c.[CONTACT_NAME], c.FLAG FROM [DATA].[DIM_CONTACT] C
INNER JOIN STAGE.FACT_NEGOTATION F ON F.contact_id = C.CONTACT_ID
AND F.HISTORY_DATE BETWEEN '2020-01-01' AND '2020-11-31';



SELECT distinct E.[RESPONSE_NAME]
      ,E.[FLAG]
  FROM [DATA_MART].[DATA].[dim_response] E
  INNER JOIN GESTIONES_COMPARTAMOS_202012 R ON R.[RESPONSE_NAME] = E.[RESPONSE_NAME];

CREATE VIEW VW_PAGOS_COMPARTAMOS AS
SELECT
C.COD_CTA AS CREDIT_CODE, 
CONVERT(DECIMAL(18,2),P.MONTO) AS AMOUNT, 
CASE RTRIM(LTRIM(P.MONEDA))
  WHEN 'S/.' THEN 'SOLES'
  WHEN 'S/' THEN 'SOLES'
  WHEN 'US$' THEN 'DOLARES' END
  AS CURRENCY, 
  CONVERT(DATE,P.F_PAGO,23) AS PAYMENT_DATE
FROM [SEGURO02_09].[DBO].[COB_PAGOS] P
INNER JOIN [SEGURO02_09].[DBO].[COB_CUENTAS1] C ON C.COD_CTACLIENTE = P.COD_CTACLIENTE
INNER JOIN DATA.DIM_CREDIT_1 CC ON CC.account_code = C.cod_cta
WHERE CC.PORTFOLIO_NAME = 'COMPARTAMOS' AND CC.NEGOTIATOR_NAME <> 'OFICINA';

WHERE C.cod_cartera = 5;

SELECT * FROM VW_PAGOS_COMPARTAMOS WHERE PAYMENT_DATE BETWEEN '2020-07-01' AND '2020-07-31';


SELECT C.cod_cartera FROM  [SEGURO02_09].[DBO].[COB_PAGOS] P
INNER JOIN [SEGURO02_09].[DBO].[COB_CUENTAS1] C ON C.COD_CTACLIENTE = P.COD_CTACLIENTE;

SELECT MONEDA FROM [SEGURO02_09].[DBO].[COB_PAGOS]
GROUP BY MONEDA;

SELECT F_PAGO FROM [SEGURO02_09].[DBO].[COB_PAGOS]
GROUP BY F_PAGO
ORDER BY F_PAGO DESC;

SELECT * FROM [SEGURO02_09].[dbo].[cob_cartera];

------

SELECT NEGOTIATOR_NAME
FROM DATA.DIM_CREDIT_1 C WHERE
C.PORTFOLIO_NAME = 'COMPARTAMOS' 
GROUP BY NEGOTIATOR_NAME
ORDER BY NEGOTIATOR_NAME;



SELECT * FROM
(SELECT C.NEGOTIATOR_NAME
FROM DATA.DIM_CREDIT_1 C WHERE
C.PORTFOLIO_NAME = 'COMPARTAMOS' 
GROUP BY NEGOTIATOR_NAME) AS C
WHERE NOT EXISTS 
(
SELECT 1 FROM DATA.DIM_NEGOTIATOR N 
WHERE N.NEGOTIATOR_NAME = C.NEGOTIATOR_NAME
) ORDER BY 1 DESC;

UPDATE DATA.DIM_NEGOTIATOR
SET NEGOTIATOR_NAME = 'JACINTO VALVERDE'
WHERE negotiator_code = 'JVALVERDE';


SELECT NEGOTIATOR_CODE, NEGOTIATOR_NAME FROM DATA.DIM_NEGOTIATOR N
 WHERE NEGOTIATOR_ID = 422814
ORDER BY 2

UPDATE DATA.DIM_CREDIT_1 
SET NEGOTIATOR_NAME = 'FIORELLA SOTACURI'
WHERE NEGOTIATOR_NAME = 'FIORELLA';

UPDATE C
SET
    C.NEGOTIATOR_NAME = E.DESPUES
FROM 
    DATA.DIM_CREDIT_1 C
    INNER JOIN VW_SIN_EJECUTIVO E
        ON C.account_code = E.account_code;


VW_SIN_EJECUTIVO


SELECT DISTINCT C.account_code, N.NEGOTIATOR_CODE, C.NEGOTIATOR_NAME AS ANTES, F.NEGOTIATOR_ID, NN.NEGOTIATOR_NAME AS DESPUES
FROM DATA.DIM_CREDIT_1 C
LEFT JOIN DATA.DIM_NEGOTIATOR N ON N.NEGOTIATOR_NAME = C.NEGOTIATOR_NAME
LEFT JOIN DATA.FACT_NEGOTATION F ON C.CREDIT_ID = F.CREDIT_ID
LEFT JOIN DATA.DIM_NEGOTIATOR NN ON NN.NEGOTIATOR_ID = F.NEGOTIATOR_ID
where C.PORTFOLIO_NAME = 'COMPARTAMOS' AND
 N.NEGOTIATOR_CODE IS NULL AND F.negotiator_id IS NOT NULL;



 UPDATE C
SET
    C.NEGOTIATOR_NAME = NN.negotiator_name
FROM 
    DATA.DIM_CREDIT_1 C
    INNER JOIN VW_NULL_EJECUTIVO R    
	LEFT JOIN DATA.DIM_NEGOTIATOR NN ON NN.NEGOTIATOR_ID = R.NEGOTIATOR_ID
 ON C.account_code = R.account_code
 AND C.NEGOTIATOR_NAME IS NULL AND C.PORTFOLIO_NAME = 'COMPARTAMOS';

 CREATE VIEW VW_NULL_EJECUTIVO AS
 SELECT DISTINCT C.account_code,
C.negotiator_name, MAX(F.NEGOTIATOR_ID) AS NEGOTIATOR_ID
FROM DATA.DIM_CREDIT_1 C
LEFT JOIN DATA.FACT_NEGOTATION F ON C.CREDIT_ID = F.CREDIT_ID
LEFT JOIN DATA.DIM_NEGOTIATOR NN ON NN.NEGOTIATOR_ID = F.NEGOTIATOR_ID
WHERE C.NEGOTIATOR_NAME IS NULL AND C.PORTFOLIO_NAME = 'COMPARTAMOS' 
GROUP BY C.account_code, C.negotiator_name;




SELECT F.negotation_id FROM DATA.fact_negotation F
INNER JOIN DATA.DIM_CREDIT_1 C ON C.credit_id = F.credit_id
WHERE C.account_code =
'032310189900'

SELECT * FROM Seguro02_09.dbo.cip_RGESTIONCP where cod_gestor = 
422814
