-- CARTERA_COMPARTAMOS_202012
--CREATE VIEW DATA.CARTERA_COMPARTAMOS_202012 AS 
SELECT DISTINCT
  C.ACCOUNT_CODE AS CREDIT_CODE,
  C.CLIENT_CODE,
  C.CLIENT_DOCN,
  C.CLIENT_NAME,
  C.PORTFOLIO_NAME,
  C.PRODUCT_NAME,
  C.PRINCIPAL_AMNT,
  C.NET_DEBT_AMNT,
  N.NEGOTIATOR_CODE,
  N.NEGOTIATOR_NAME
FROM DATA.DIM_CREDIT_1 C
INNER JOIN DATA.DIM_NEGOTIATOR N ON N.NEGOTIATOR_NAME = C.NEGOTIATOR_NAME
LEFT JOIN STAGE.FACT_NEGOTATION F ON C.CREDIT_ID = F.CREDIT_ID
LEFT JOIN  [SEGURO02_09].[DBO].[COB_PAGOS] P ON P.cod_ctacliente = C.credit_id
WHERE
C.PORTFOLIO_NAME = 'COMPARTAMOS' AND
(F.HISTORY_DATE BETWEEN '2020-11-01' AND '2020-11-30'
OR CONVERT(DATE,C.CREATION_DATE,23) BETWEEN '2020-11-01' AND '2020-11-30'
OR CONVERT(DATE,P.F_PAGO,23) BETWEEN '2020-11-01' AND '2020-11-30');

SELECT PRODUCT_NAME FROM DATA.DIM_CREDIT_1 WHERE
PORTFOLIO_NAME = 'COMPARTAMOS'
AND CONVERT(DATE,CREATION_DATE,23) >= '2020-01-01'
GROUP BY PRODUCT_NAME;

-- GESTIONES_COMPARTAMOS_202012
SELECT * FROM GESTIONES_COMPARTAMOS_202012;

--CREATE VIEW  GESTIONES_COMPARTAMOS_202012 AS
SELECT DISTINCT
    C.ACCOUNT_CODE AS CREDIT_CODE,
    A.ACTION_NAME,
    RP.RESPONSE_NAME,
    CO.CONTACT_NAME,
    ---CAST(F.REASON_ID AS INTEGER) AS REASON_ID,
    N.NEGOTIATOR_CODE,
    E.CARRIER_NAME,
    CONVERT(DATE, F.HISTORY_DATE, 23) AS HISTORY_DATE,
	REPLACE(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(UPPER(F.OBSERVATION))),CHAR(9),''), CHAR(13), ''), CHAR(10), ''),'"','') AS OBSERVATION,
    F.TELEPHONE_NUMBER,
    REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(UPPER(F.TELEPHONE_STATUS))),CHAR(9),''), CHAR(13), ''), CHAR(10), '') AS TELEPHONE_STATUS,
    CONVERT(DECIMAL(15,2), F.PROMISE_AMNT) AS PROMISE_AMNT,
    CONVERT(DATE, F.PROMISE_NEXT_DATE, 23) AS PROMISE_NEXT_DATE,
    F.FLAG
  FROM STAGE.FACT_NEGOTATION F
  INNER JOIN DATA.DIM_CREDIT_1 C ON C.CREDIT_ID = F.CREDIT_ID
  INNER JOIN DATA.DIM_NEGOTIATOR N ON N.NEGOTIATOR_ID = F.NEGOTIATOR_ID
  INNER JOIN DATA.CARTERA_COMPARTAMOS_202012 O ON (N.NEGOTIATOR_CODE = O.NEGOTIATOR_CODE AND O.CREDIT_CODE = C.ACCOUNT_CODE)
  INNER JOIN DATA.DIM_ACTION A ON A.ACTION_ID = F.ACTION_ID
  INNER JOIN DATA.DIM_RESPONSE RP ON RP.RESPONSE_ID = F.RESPONSE_ID
  INNER JOIN DATA.DIM_CONTACT CO ON CO.CONTACT_ID = F.CONTACT_ID
  LEFT JOIN DATA.DIM_CARRIER E ON E.CARRIER_ID = F.CARRIER_ID
  WHERE C.FLAG = 1 AND F.HISTORY_DATE BETWEEN '2020-11-01' AND '2020-11-31'
  AND C.PORTFOLIO_NAME = 'COMPARTAMOS'
 -- AND CONVERT(DATE,C.CREATION_DATE,23) BETWEEN '2020-01-01' AND  '2020-01-30'
 -- ORDER BY F.HISTORY_DATE ASC;


  -- DIMENSIONES
  SELECT ACTION_NAME , FLAG FROM DATA.dim_action;

SELECT  distinct c.[CONTACT_NAME], c.FLAG FROM [DATA].[DIM_CONTACT] C
INNER JOIN STAGE.FACT_NEGOTATION F ON F.contact_id = C.CONTACT_ID
AND F.HISTORY_DATE BETWEEN '2020-01-01' AND '2020-11-31';

''

SELECT distinct E.[RESPONSE_NAME]
      ,E.[FLAG]
  FROM [DATA_MART].[DATA].[dim_response] E
  INNER JOIN GESTIONES_COMPARTAMOS_202012 R ON R.[RESPONSE_NAME] = E.[RESPONSE_NAME];


SELECT
C.COD_CTA AS CREDIT_CODE, 
CONVERT(DECIMAL(18,2),P.MONTO) AS AMOUNT, 
CASE RTRIM(LTRIM(P.MONEDA))
  WHEN 'S/.' THEN 'SOLES'
  WHEN 'S/' THEN 'SOLES'
  WHEN 'US$' THEN 'DOLARES' END
  AS CURRENCY, 
P.F_PAGO AS PAYMENT_DATE
FROM [SEGURO02_09].[DBO].[COB_PAGOS] P
INNER JOIN [SEGURO02_09].[DBO].[COB_CUENTAS1] C ON C.COD_CTACLIENTE = P.COD_CTACLIENTE
WHERE
CONVERT(DATE,P.F_PAGO,23) BETWEEN '2020-01-01' AND  '2020-01-31'


SELECT MONEDA FROM [SEGURO02_09].[DBO].[COB_PAGOS]
GROUP BY MONEDA;

SELECT F_PAGO FROM [SEGURO02_09].[DBO].[COB_PAGOS]
GROUP BY F_PAGO
ORDER BY F_PAGO DESC;